# Generated by Django 4.2.8 on 2025-01-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'حساب\u200cهای کاربری', 'verbose_name_plural': 'حساب\u200cهای کاربری'},
        ),
    ]
