# Generated by Django 4.2.8 on 2025-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='brands_on',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
