# Generated by Django 4.2.8 on 2025-01-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_store_brands_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='brands_on',
            new_name='show_brands',
        ),
    ]
