# Generated by Django 4.2.8 on 2025-01-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_brands_on_store_show_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='show_brands',
            field=models.BooleanField(default=False),
        ),
    ]
