# Generated by Django 4.2.8 on 2025-01-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_store_show_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.TextField(default='توضیحات لازم در مورد شیوه\u200cهای ارسال، مدت زمان انتظار و هزینه ارسال کالا')),
                ('payment', models.TextField(verbose_name='معرفی شیوه\u200cهای پرداختی که در فروشگاه امکان\u200cپذیر است')),
                ('returns', models.TextField(verbose_name='توضیح صریح سیاست\u200cهای مرجوعی و بازپرداخت وجه کالاهای عودت داده شده')),
                ('rules_and_policies', models.TextField(verbose_name='قوانین و مقررات کلی سایت و سیاست\u200cهای حریم خصوصی')),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='policies',
        ),
    ]
