# Generated by Django 4.2.8 on 2025-01-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_policy_remove_store_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='payment',
            field=models.TextField(default='معرفی شیوه\u200cهای پرداختی که در فروشگاه امکان\u200cپذیر است'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='returns',
            field=models.TextField(default='توضیح صریح سیاست\u200cهای مرجوعی و بازپرداخت وجه کالاهای عودت داده شده'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='rules_and_policies',
            field=models.TextField(default='قوانین و مقررات کلی سایت و سیاست\u200cهای حریم خصوصی'),
        ),
    ]
