# Generated by Django 4.2.8 on 2025-01-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_policy_payment_alter_policy_returns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='about_description',
            field=models.TextField(default='درباره فروشگاه، خدمات و سوابق آن'),
        ),
    ]
