# Generated by Django 4.2.8 on 2025-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_store_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
