# Generated by Django 4.2.8 on 2025-01-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_store_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
    ]
