# Generated by Django 4.2.8 on 2025-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='meta_description',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با سایت ساز رایگان پیکوسایت'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_keywords',
            field=models.TextField(default='ساخته شده با فروشگاه ساز پیکوسایت, فروشگاه اینترنتی, فروشگاه آنلاین, سایت ساز پیکوسایت'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_og_description',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با پیکوسایت'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_og_title',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با پیکوسایت'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_tc_description',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با پیکوسایت'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_tc_title',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با پیکوسایت'),
        ),
    ]
