# Generated by Django 4.2.8 on 2025-01-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_store_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tag',
            field=models.ManyToManyField(blank=True, to='shop.tag'),
        ),
    ]
