# Generated by Django 4.2.8 on 2025-01-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_banner_category_alter_banner_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'قوانین و سیاست\u200cها'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='delivery',
            field=models.TextField(default='توضیحات لازم در مورد شیوه\u200cهای ارسال، مدت زمان انتظار و هزینه ارسال کالا', verbose_name='شیوه ارسال'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='payment',
            field=models.TextField(default='معرفی شیوه\u200cهای پرداختی که در فروشگاه امکان\u200cپذیر است', verbose_name='شیوه\u200cهای پرداخت'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='returns',
            field=models.TextField(default='توضیح صریح سیاست\u200cهای مرجوعی و بازپرداخت وجه کالاهای عودت داده شده', verbose_name='سیاست\u200cهای مرجوعی'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='rules_and_policies',
            field=models.TextField(default='قوانین و مقررات کلی سایت و سیاست\u200cهای حریم خصوصی', verbose_name='قوانین و مقررات'),
        ),
    ]
