# Generated by Django 4.2.8 on 2025-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ref_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ref_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
