# Generated by Django 4.2.8 on 2025-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'قوانین و سیاست\u200cها', 'verbose_name_plural': 'قوانین و سیاست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='Layout_body',
        ),
        migrations.RemoveField(
            model_name='store',
            name='active_days',
        ),
        migrations.RemoveField(
            model_name='store',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='store',
            name='domain_msg',
        ),
        migrations.RemoveField(
            model_name='store',
            name='gw_msg',
        ),
        migrations.RemoveField(
            model_name='store',
            name='has_notif',
        ),
        migrations.RemoveField(
            model_name='store',
            name='independent',
        ),
        migrations.RemoveField(
            model_name='store',
            name='layout_container',
        ),
        migrations.RemoveField(
            model_name='store',
            name='layout_sticky',
        ),
        migrations.AlterField(
            model_name='store',
            name='about_description',
            field=models.TextField(default='درباره فروشگاه، خدمات و سوابق آن', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default='tehran', max_length=250, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='store',
            name='color',
            field=models.CharField(default='0,0,0', max_length=250, verbose_name='رنگ اصلی'),
        ),
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(default='iran', max_length=250, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='دامنه'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='store',
            name='enamad_code',
            field=models.CharField(blank=True, default='none', max_length=1000, null=True, verbose_name='کد ای\u200cنماد'),
        ),
        migrations.AlterField(
            model_name='store',
            name='has_domain',
            field=models.BooleanField(default=False, verbose_name='دامنه فعال'),
        ),
        migrations.AlterField(
            model_name='store',
            name='has_payment_gw',
            field=models.BooleanField(default=False, verbose_name='درگاه پرداخت فعال'),
        ),
        migrations.AlterField(
            model_name='store',
            name='index_title',
            field=models.CharField(blank=True, default='خانه', max_length=250, null=True, verbose_name='عنوان صفحه نخست'),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='store',
            name='linkedin',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='store',
            name='merchant',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='مرچنت کد'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_description',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با سایت ساز رایگان پیکوسایت', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_keywords',
            field=models.TextField(default='ساخته شده با فروشگاه ساز پیکوسایت, فروشگاه اینترنتی, فروشگاه آنلاین, سایت ساز پیکوسایت', verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_og_description',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با پیکوسایت', verbose_name='توضیحات OpenGrapg'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_og_title',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با پیکوسایت', verbose_name='عنوان OpenGrapg'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_tc_description',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با پیکوسایت', verbose_name='توضیحات کارت توییتر'),
        ),
        migrations.AlterField(
            model_name='store',
            name='meta_tc_title',
            field=models.TextField(default='فروشگاه اینترنتی ساخته شده با پیکوسایت', verbose_name='عنوان کارت توییتر'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='store',
            name='show_brands',
            field=models.BooleanField(default=False, verbose_name='نمایش برندها'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='store',
            name='template_index',
            field=models.IntegerField(default=1, verbose_name='شماره قالب'),
        ),
    ]
