# Generated by Django 4.2.8 on 2025-01-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_policy_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultcategory',
            options={'ordering': ('name',), 'verbose_name': 'دسته\u200cبندی\u200cها', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterField(
            model_name='defaultcategory',
            name='is_sub',
            field=models.BooleanField(default=False, verbose_name='آیا زیردسته است؟'),
        ),
        migrations.AlterField(
            model_name='defaultcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='عنوان دسته'),
        ),
        migrations.AlterField(
            model_name='defaultcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='shop.defaultcategory', verbose_name='دسته\u200cبندی مادر'),
        ),
        migrations.AlterField(
            model_name='defaultcategory',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='نامک'),
        ),
    ]
