# Generated by Django 4.2.8 on 2025-01-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_defaultcategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductRefClass',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'دسته\u200cبندی\u200cهای محصولات', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصولات'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتریان', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='defaultcategory',
            options={'ordering': ('name',), 'verbose_name': 'دسته\u200cبندی\u200cهای پیش\u200cفرض', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای پیش\u200cفرض'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'شیوه\u200cهای ارسال', 'verbose_name_plural': 'شیوه\u200cهای ارسال'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'ویژگی\u200cها', 'verbose_name_plural': 'ویژگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created'], 'verbose_name': 'کدهای OTP', 'verbose_name_plural': 'کدهای OTP'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'مدیران فروشگاه', 'verbose_name_plural': 'مدیران فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='pricerange',
            options={'verbose_name': 'رنج\u200cهای قیمتی', 'verbose_name_plural': 'رنج\u200cهای قیمتی'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ\u200cها', 'verbose_name_plural': 'تگ\u200cها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_sub',
            field=models.BooleanField(default=False, verbose_name='معرفی به عنوان زیردسته'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='shop.category', verbose_name='دسته\u200cبندی مادر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='نام محله - بلوار اصلی - خیابان اصلی - خیابان فرعی - کوچه - پلاک - واحد', max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Tehran', max_length=250, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='علاقمندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='کاربر میهمان', max_length=250, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='otp_token',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد OTP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet_balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='اعتبار کیف پول'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default='1234567890', max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='min_cart_free',
            field=models.IntegerField(default=2000000, verbose_name='حداقل مبلغ سبد برای ارسال رایگان'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='min_cart_free_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن ارسال رایگان برای مبالغ بالا'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.IntegerField(verbose_name='هزینه (تومان)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='value',
            field=models.CharField(max_length=250, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='max_value',
            field=models.IntegerField(verbose_name='بیشترین مقدار'),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='min_value',
            field=models.IntegerField(verbose_name='کمترین مقدار'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='تگ ویژه'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='نامک'),
        ),
    ]
