# Generated by Django 4.2.8 on 2025-01-23 08:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_otpcode_code_alter_otpcode_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpressDeliveryInterval',
        ),
        migrations.DeleteModel(
            name='Recommender',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='ticket',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created',), 'verbose_name': 'اطلاعیه\u200cها', 'verbose_name_plural': 'اطلاعیه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('created',), 'verbose_name': 'بنرها', 'verbose_name_plural': 'بنرها'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'دسته\u200cبندی\u200cهای مقالات', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقالات'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-created_date',), 'verbose_name': 'مقالات وبلاگ', 'verbose_name_plural': 'مقالات وبلاگ'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برندها', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبدهای خرید مشتریان', 'verbose_name_plural': 'سبدهای خرید مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'آیتم\u200cهای سبد خرید', 'verbose_name_plural': 'آیتم\u200cهای سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='cashback',
            options={'verbose_name': 'کش\u200cبک', 'verbose_name_plural': 'کش\u200cبک'},
        ),
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'ordering': ('-created',), 'verbose_name': 'تصویر دسته\u200cبندی', 'verbose_name_plural': 'تصویر دسته\u200cبندی'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',), 'verbose_name': 'دیدگاه\u200cها', 'verbose_name_plural': 'دیدگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('-created',), 'verbose_name': 'پیام\u200cها', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'کدهای تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('-created_date',), 'verbose_name': 'دامنه\u200cی سایت', 'verbose_name_plural': 'دامنه\u200cی سایت'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوالات متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='featuredcategories',
            options={'verbose_name': 'دسته\u200cبندی\u200cهای شاخص', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای شاخص'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'فیلترهای دسته\u200cبندی\u200cهای محصولات', 'verbose_name_plural': 'فیلترهای دسته\u200cبندی\u200cهای محصولات'},
        ),
        migrations.AlterModelOptions(
            name='filtervalue',
            options={'verbose_name': 'مقادیر فیلترها', 'verbose_name_plural': 'مقادیر فیلترها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_date',), 'verbose_name': 'سفارشات', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'وضعیت\u200cهای سفارشات خرید', 'verbose_name_plural': 'وضعیت\u200cهای سفارشات خرید'},
        ),
        migrations.AlterModelOptions(
            name='postthumbnail',
            options={'ordering': ('-created',), 'verbose_name': 'لوگوی فروشگاه', 'verbose_name_plural': 'لوگوی فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productfilter',
            options={'verbose_name': 'فیلترهای محصولات', 'verbose_name_plural': 'فیلترهای محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('created',), 'verbose_name': 'تصاویر محصولات', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('created',), 'verbose_name': 'اسلایدها', 'verbose_name_plural': 'اسلایدها'},
        ),
        migrations.AlterModelOptions(
            name='storelogoimage',
            options={'ordering': ('created',), 'verbose_name': 'لوگوی فروشگاه', 'verbose_name_plural': 'لوگوی فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک\u200cها', 'verbose_name_plural': 'اشتراک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='uploadedimages',
            options={'verbose_name': 'تصاویر آپلود شده', 'verbose_name_plural': 'تصاویر آپلود شده'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name': 'تنوع محصولات', 'verbose_name_plural': 'تنوع محصولات'},
        ),
        migrations.AlterModelOptions(
            name='withdrawrecord',
            options={'ordering': ('-created_date',), 'verbose_name': 'درخواست\u200cهای برداشت وجه', 'verbose_name_plural': 'درخواست\u200cهای برداشت وجه'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='has_express_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='has_normal_items',
        ),
        migrations.RemoveField(
            model_name='postthumbnail',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='storelogoimage',
            name='custom_name',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(verbose_name='متن اطلاعیه'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='alt_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان جایگزین'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.category', verbose_name='دسته\u200cبندی محصولات هدف'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='media/11.png', upload_to=shop.models.banner_upload_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.PositiveIntegerField(default=1, verbose_name='شماره بنر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='size',
            field=models.CharField(default='small', max_length=250, verbose_name='سایز بنر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tag',
            field=models.ManyToManyField(blank=True, to='shop.tag', verbose_name='تگ محصولات هدف'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=250, verbose_name='عنوان دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor.fields.RichTextField(default='insert the post body', verbose_name='متن مقاله'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.blogcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(default='', max_length=500, verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(default='', max_length=500, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_og_description',
            field=models.CharField(default='', max_length=1000, verbose_name='توضیحات OpenGraph'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_og_title',
            field=models.CharField(default='', max_length=250, verbose_name='عنوان OpenGraph'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_tc_description',
            field=models.CharField(default='', max_length=250, verbose_name='توضیحات TwitterCard'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_tc_title',
            field=models.CharField(default='', max_length=250, verbose_name='عنوان TwitterCard'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=250, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='shop.cartitem', verbose_name='آیتم\u200cهای سبد خرید'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.variety', verbose_name='تنوع کالا'),
        ),
        migrations.AlterField(
            model_name='cashback',
            name='const',
            field=models.IntegerField(default=0, verbose_name='مقدار ثابت'),
        ),
        migrations.AlterField(
            model_name='cashback',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='درصد'),
        ),
        migrations.AlterField(
            model_name='cashback',
            name='repetation',
            field=models.IntegerField(default=0, verbose_name='تکرار'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='alt_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان جایگزین'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(default='media/11.png', upload_to=shop.models.category_upload_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='تایید نمایش'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='متن دیدگاه'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='فرستنده'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='familly_name',
            field=models.CharField(max_length=250, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='رسیدگی شده'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=ckeditor.fields.RichTextField(default='پیام خود را وارد نمایید.', verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=100, verbose_name='نام دامنه'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=2000, verbose_name='متن پاسخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, verbose_name='متن پرسش'),
        ),
        migrations.AlterField(
            model_name='featuredcategories',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shop.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=250, verbose_name='عنوان فیلتر'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.filter', verbose_name='عنوان فیلتر'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_values', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='value',
            field=models.CharField(max_length=250, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سفارش و ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.delivery', verbose_name='شیوه ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_off',
            field=models.BooleanField(default=False, verbose_name='ارسال رایگان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shop.cartitem', verbose_name='آیتم\u200cها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_by_wallet',
            field=models.IntegerField(default=0, verbose_name='میزان پرداخت با کیف پول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شهر تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='ایمیل تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_familly_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام خانوادگی تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_state',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='استان تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_zip_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='کد پستی تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.orderstatus', verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_updated_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='used_coupon',
            field=models.BooleanField(default=False, verbose_name='استفاده از کوپن تخفیف'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='latest_status',
            field=models.CharField(max_length=250, verbose_name='عنوان وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='متفرقه', max_length=255, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=ckeditor.fields.RichTextField(verbose_name='ویژگی\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OpenGraph'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_og_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان OpenGraph'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_tc_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات TwitterCard'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_tc_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان TwitterCard'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن فروش با تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف\u200cدار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_alarm_volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='هشدار اتمام موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, verbose_name='بازدیدها'),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.filter', verbose_name='فیلتر'),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='values',
            field=models.ManyToManyField(blank=True, to='shop.filtervalue', verbose_name='مقدار فیلتر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='نام جایگزین'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='media/11.png', upload_to=shop.models.image_upload_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='alt_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان جایگزین'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='category',
            field=models.ManyToManyField(to='shop.category', verbose_name='دسته\u200cبندی محصولات هدف'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(default='media/11.png', upload_to=shop.models.slide_upload_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='index',
            field=models.PositiveIntegerField(default=1, verbose_name='شماره اسلاید'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='tag',
            field=models.ManyToManyField(to='shop.tag', verbose_name='تگ محصولات هدف'),
        ),
        migrations.AlterField(
            model_name='storelogoimage',
            name='alt_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام جایزگین'),
        ),
        migrations.AlterField(
            model_name='storelogoimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='storelogoimage',
            name='image',
            field=models.ImageField(default='media/11.png', upload_to=shop.models.logo_upload_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='alt_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان دلخواه'),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='name',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='تعداد موجود در انبار'),
        ),
        migrations.AlterField(
            model_name='withdrawrecord',
            name='amount',
            field=models.IntegerField(verbose_name='مبلغ به تومان'),
        ),
        migrations.AlterField(
            model_name='withdrawrecord',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='withdrawrecord',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='withdrawrecord',
            name='sheba',
            field=models.CharField(max_length=250, verbose_name='شماره شبا'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
    ]
