# Generated by Django 4.2.8 on 2025-01-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_delete_expressdeliveryinterval_delete_recommender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(default='', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.TextField(default='', verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_og_description',
            field=models.TextField(default='', verbose_name='توضیحات OpenGraph'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_og_title',
            field=models.TextField(default='', verbose_name='عنوان OpenGraph'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_tc_description',
            field=models.TextField(default='', verbose_name='توضیحات TwitterCard'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_tc_title',
            field=models.TextField(default='', verbose_name='عنوان TwitterCard'),
        ),
    ]
