# Generated by Django 4.2.8 on 2025-01-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default='نام محله - بلوار اصلی - خیابان اصلی - خیابان فرعی - کوچه - پلاک - واحد', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس تحویل گیرنده'),
        ),
    ]
