# Generated by Django 4.2.8 on 2024-12-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_announcement_store_remove_banner_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_original',
        ),
    ]
