# Generated by Django 4.2.8 on 2025-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_customer_address_alter_order_reciever_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sho_blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sho_specials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='show_advantages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='show_featured_categories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='show_special_offer',
            field=models.BooleanField(default=True),
        ),
    ]
