# Generated by Django 4.2.8 on 2025-01-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_store_sho_blog_store_sho_specials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='sho_blog',
            new_name='show_blog',
        ),
    ]
