# Generated by Django 4.2.8 on 2024-12-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_coupon_discount_remove_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='میزان تخفیف (تومان)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_cart_volume',
            field=models.IntegerField(default=0, verbose_name='حداقل مبلغ سبد خرید (تومان)'),
        ),
    ]
