# Generated by Django 4.2.8 on 2024-12-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_coupon_discount_percentage_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='source',
        ),
        migrations.AddField(
            model_name='slide',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
        migrations.AddField(
            model_name='slide',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),
    ]
