# Generated by Django 4.2.8 on 2024-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_slide_source_slide_category_slide_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='source',
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),
    ]
