# Generated by Django 4.2.8 on 2025-01-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_rename_sho_specials_store_show_specials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='show_advantages',
            field=models.BooleanField(default=True, verbose_name='نمایش نقاط قوت فروشگاه'),
        ),
        migrations.AlterField(
            model_name='store',
            name='show_blog',
            field=models.BooleanField(default=True, verbose_name='نمایش وبلاگ'),
        ),
        migrations.AlterField(
            model_name='store',
            name='show_featured_categories',
            field=models.BooleanField(default=True, verbose_name='نمایش دسته\u200cبندی\u200cهای ویژه'),
        ),
        migrations.AlterField(
            model_name='store',
            name='show_special_offer',
            field=models.BooleanField(default=True, verbose_name='نمایش پیشنهادات شگفت\u200cانگیز'),
        ),
        migrations.AlterField(
            model_name='store',
            name='show_specials',
            field=models.BooleanField(default=True, verbose_name='نمایش محصولات ویژه'),
        ),
    ]
