# Generated by Django 4.2.8 on 2024-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_productfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='value',
            field=models.ManyToManyField(blank=True, to='shop.filtervalue'),
        ),
    ]
