# Generated by Django 4.2.8 on 2024-12-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_filtervalue_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtervalue',
            name='product',
        ),
        migrations.AddField(
            model_name='filtervalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_values', to='shop.product'),
        ),
    ]
