# Generated by Django 4.2.8 on 2024-12-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_blogcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='slug',
        ),
    ]
